version: "3.4"

services:
  api:
    build: .
    ports:
      - 8081:5000
    volumes:
      - ./:/usr/src/api
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.28
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sidia
      - MYSQL_ROOT_PASSWORD=root